# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nfcovid-1.0
channels:
  - conda-forge
  - bioconda
  - defaults
  - hcc
dependencies:
  ## conda-forge packages
  - conda-forge::python=3.6.10
  - conda-forge::markdown=3.2.2
  - conda-forge::pymdown-extensions=7.1
  - conda-forge::pygments=2.6.1
  - conda-forge::pigz=2.3.4
  - conda-forge::bc=1.07.1
  - conda-forge::r-base=3.6.2
  - conda-forge::r-optparse=1.6.6
  - conda-forge::r-tidyr=1.1.0
  - conda-forge::r-tidyverse=1.3.0
  - conda-forge::r-ggplot2=3.3.1
  - conda-forge::r-reshape2=1.4.4
  - conda-forge::r-viridis=0.5.1

  ## bioconda packages
  ## common
  - bioconda::fastqc=0.11.9
  - bioconda::parallel-fastq-dump=0.6.6
  - bioconda::fastp=0.20.1
  - bioconda::samtools=1.9
  - bioconda::bedtools=2.29.2
  - bioconda::multiqc=1.9
  - bioconda::bamclipper=1.0.0
  - bioconda::trimmomatic=0.39

  ## variants
  - bioconda::bowtie2=2.4.1
  - bioconda::mosdepth=0.2.6
  - bioconda::ivar=1.2.2
  - bioconda::bcftools=1.9
  - bioconda::varscan=2.4.4
  - bioconda::snpeff=4.5covid19
  - bioconda::snpsift=4.3.1t
  - bioconda::bioconductor-complexheatmap=2.2.0
  - bioconda::bioconductor-biostrings=2.54.0


